apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: dind-sidecar-
spec:
  taskSpec:
    steps:
    - image: docker
      name: client
      env:
      # Connect to the sidecar over TCP without TLS.
      - name: DOCKER_HOST
        value: tcp://localhost:2375
      script: |
          #!/usr/bin/env sh
          # Run a Docker container.
          docker run busybox echo hello

          # Write a Dockerfile and `docker build` it.
          cat > Dockerfile << EOF
          FROM ubuntu
          RUN apt-get update
          ENTRYPOINT ["echo", "hello"]
          EOF
          docker build -t hello . && docker run hello
          docker images

          # ...then run it!
          docker run hello
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket

    sidecars:
    - image: docker:dind
      name: server
      securityContext:
        privileged: true
      env:
      # This disables TLS for TCP connections between the sidecar and client step.
      - name: DOCKER_TLS_CERTDIR
        value: ''
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket

    volumes:
    - name: dind-socket
      emptyDir: {}
