apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: home-volume-
spec:
  taskSpec:
    steps:
    - name: write
      image: ubuntu
      command: ['bash']
      args: ['-c', 'echo some stuff > /tekton/home/stuff']
    - name: read
      image: ubuntu
      command: ['cat']
      args: ['/tekton/home/stuff']
    - name: override-homevol
      image: ubuntu
      command: ['bash']
      # /tekton/home/stuff *doesn't* exist.
      args: ['-c', '[[ ! -f /tekton/home/stuff ]]']
      volumeMounts:
      - name: empty
        mountPath: /tekton/home
    volumes:
    - name: empty
      emptyDir: {}
