baseImageOverrides:
  github.com/knative/build-pipeline/vendor/github.com/knative/build/cmd/creds-init: gcr.io/knative-releases/github.com/knative/build-pipeline/build-base:latest
  github.com/knative/build-pipeline/vendor/github.com/knative/build/cmd/git-init: gcr.io/knative-releases/github.com/knative/build-pipeline/build-base:latest
