# Copyright 2019 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: test-task
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-task-controller
  namespace: test-task
  labels:
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-task-controller-cluster-access
  labels:
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task
rules:
    # Controller needs cluster access to all Run CRs.
  - apiGroups: ["tekton.dev"]
    resources: ["runs"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["runs/finalizers"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["runs/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

    # Controller needs permission to emit events associated with Run CRs.
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-task-controller
  namespace: test-task
  labels:
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "watch"]
  # The controller needs access to these configmaps for logging information and runtime configuration.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
    resourceNames: ["config-logging", "config-observability", "config-leader-election"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: test-task-controller
  namespace: test-task
  labels:
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task
subjects:
  - kind: ServiceAccount
    name: test-task-controller
    namespace: test-task
roleRef:
  kind: Role
  name: test-task-controller
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: test-task-controller-cluster-access
  labels:
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task
subjects:
  - kind: ServiceAccount
    name: test-task-controller
    namespace: test-task
roleRef:
  kind: ClusterRole
  name: test-task-controller-cluster-access
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: test-task
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task
data:
  # Common configuration for all knative codebase
  zap-logger-config: |
    {
      "level": "info",
      "development": false,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": ["stdout"],
      "errorOutputPaths": ["stderr"],
      "encoding": "json",
      "encoderConfig": {
        "timeKey": "",
        "levelKey": "level",
        "nameKey": "logger",
        "callerKey": "caller",
        "messageKey": "msg",
        "stacktraceKey": "stacktrace",
        "lineEnding": "",
        "levelEncoder": "",
        "timeEncoder": "",
        "durationEncoder": "",
        "callerEncoder": ""
      }
    }

  # Log level overrides
  loglevel.controller: "info"
  loglevel.webhook: "info"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-task-controller
  namespace: test-task
  labels:
    app.kubernetes.io/name: test-task-controller
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: test-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-task-controller
      app.kubernetes.io/component: test-task-controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: test-task
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app.kubernetes.io/name: test-task-controller
        app.kubernetes.io/component: test-task-controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: devel
        app.kubernetes.io/part-of: test-task
        app: test-task-controller
    spec:
      serviceAccountName: test-task-controller
      containers:
      - name: test-task-controller
        image: ko://github.com/tektoncd/pipeline/cmd/test-task
        volumeMounts:
        - name: config-logging
          mountPath: /etc/config-logging
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # If you are changing these names, you will also need to update
        # the controller's Role in 200-role.yaml to include the new
        # values in the "configmaps" "get" rule.
        - name: CONFIG_LOGGING_NAME
          value: config-logging
      volumes:
        - name: config-logging
          configMap:
            name: config-logging
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: test-task-controller
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: test-task
    # tekton.dev/release value replaced with inputs.params.versionTag in pipeline/tekton/publish.yaml
    pipeline.tekton.dev/release: "devel"
    # labels below are related to istio and should not be used for resource lookup
    app: test-task-controller
    version: "devel"
  name: test-task-controller
  namespace: test-task
spec:
  ports:
  - name: http-metrics
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: test-task-controller
    app.kubernetes.io/component: test-task-controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: test-task
